### ISSUE TITLE
how to extract those ZST_blocks file format?

### ISSUE THREAD

**Issue by kkort2022** [ArthurHeitmann/zst_blocks_format#2]
how to extract those ZST_blocks file format?

for normal zst files I am using PEAzip, but that does not work  !?

**Comment by ArthurHeitmann** [comment]
What exactly do you want to do? The files contain just lines of json strings. All the important commands are documented [here](https://github.com/ArthurHeitmann/zst_blocks_format/tree/master/python_cli). Or you can use the example script from [here](https://github.com/ArthurHeitmann/arctic_shift), if you want to iterate over all the objects in python.

**Comment by kkort2022** [comment]
I am using some php parser for crawling

I just want to collect links just like:

https://www.reddit.com/r/cats/comments/18st9t7/majestic_picture/

I do crawl by sub-reddit naming...

https://www.reddit.com/r/cats/comments/18st9t7/majestic_picture/
I think this is called submissions not comments, even if the url slug has '/comments/'

**Comment by ArthurHeitmann** [comment]
Unless you have a lot a lot of storage space, you should try to not extract the entire files, and instead only read why you currently need. With the python cli I've linked above, you can decode a file and write it to stdout or to a file.
